### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fisher60** [fisher60/friendo-collections#2]
# Project Roadmap
- [ ] Research and implement blockchain structure
  - [x] Centralized
  - [ ] Determine hashing algorithm/method
  - [ ] Incorporate discord user ID into blockchain as `owner` of block
  - [ ] Determine scarcity method (New collectibles can ONLY be created by our server and be redeemed based on some type of score/currency? Or can they be generated by users based on a scarce recourse they posses? Message count incorporated into block?)
- [ ] Develop simple API
  - [ ] Implement Auth (JWT OAuth is fine, or even just an API key. The only client should be the bot.)
  - [ ] GET list of all collectibles a user owns (probably just a list of IDs
  - [ ] GET collectible by ID
  - [ ] Confirm current ownership of collectible 
  - [ ] POST to transfer ownership from one user to another (should add another block, should it take into account that user's scarcity/currency?)
  - [ ] Discuss possibility of POST request to exchange currency from one user to another and transfer a collectible in return
- [ ] Create Database
  - [ ] Dockerized PostgreSQL
